### ISSUE TITLE
How to query ALL contigs?

### ISSUE THREAD

**Issue by projectoriented** [mrvollger/SafFire#5]
Hello 👋 !

Thank you for this awesome visualization tool. I want to batch download a specific contig for each query genome and it has been going great. However, for certain query contigs, it only only shows 1 contig. Is there a param to have it render all in this request?

`"http://127.0.0.1:5500/#dataset=quads&ref=GRCh38&query=$contig&pos=chrX&save=1"`

Thanks in advance 😃

**Comment by mrvollger** [comment]
I think I don't understand the question because when I run a similar command I do see all the query contigs. e.g:
https://mrvollger.github.io/SafFire/#dataset=HPRC&ref=CHM13_v1.1&query=HG002_1&pos=chr1:130000000-145000000

Can you elaborate a little more?

**Comment by projectoriented** [comment]
The default rendering for specific contig A in query genome A:
![SafFire_chr1_1-248956422](https://user-images.githubusercontent.com/25568561/185458290-93a96f2a-f451-4bcb-a69e-08e13c7f91d4.svg)

When I select 'All' for specific contig A in query genome A:
![SafFire_chr1_1-248956422 (1)](https://user-images.githubusercontent.com/25568561/185458602-9a69f3fa-04ff-47c3-916d-ef6cfd40b0f8.svg)

**Comment by mrvollger** [comment]
https://github.com/mrvollger/SafFire/blob/2f8fbdff4bfcef34255efaa8d7eca3ff26e1199b/lib.js#L553-L557

I think I found the offending lines. If there are more than 30 contigs it defaults to showing only the largest, which was important in some renderings. But it looks like you have your own cloned version so you should be able to just edit this line to ~500 or something for you local version. This is just a guess since I have not tested, but I think might be the issue.

**Comment by projectoriented** [comment]
Wonderful! I suspected it was that as well and commented it out yesterday but didn't clear my browser cookies and thought the problem lie somewhere else. In any case, it works! Thank you for your help 🚀 !
